services:
  db:
    container_name: bookflixDB
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ch4Ch1t417
      POSTGRES_DB: postgres
      PGDATA: /Program Files/PostgreSQL/16/data
    volumes:
      - db:/Program Files/PostgreSQL/16/data
    ports:
      - "5332:5432"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
